name: LINE Bot Message Scheduler

on:
  workflow_dispatch:       # 手動実行
  schedule:
    - cron: "0 * * * *"

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Debug - List all files
      run: ls -R

    - name: Debug - Print environment variables
      run: |
        echo "LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}"
        echo "LINE_GROUP_ID=${LINE_GROUP_ID}"
        echo "GEMINI_API_KEY=${GEMINI_API_KEY}"
      env:
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    - name: Send LINE message
      env:
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_GROUP_ID: ${{ secrets.LINE_GROUP_ID }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python src/main.py
